REM Start script for windows
REM based on https://www.pythonguis.com/tutorials/packaging-pyqt5-pyside2-applications-windows-pyinstaller/

:::::::::::::::::::::
REM Environment setup
:::::::::::::::::::::

REM If applicable perform clean install of virtual environment 
REM call setup/create_env.bat
call activate esibd

:::::::::::::::::::::::::::
REM Sphinx -> read the docs
:::::::::::::::::::::::::::

REM use sphinx-quickstart to generate initial configuration
REM then edit docs/conf.py to customize
call rmdir /q /s docs\_build REM delete docs/_build to generate clean documentation
REM call rmdir /q /s docs\autoapi REM delete docs/_build to generate clean documentation
REM call rm -r docs\_build REM delete docs/_build to generate clean documentation (works in powershell?)
call sphinx-build docs docs\_build REM -M coverage
call docs\make.bat html

:::::::::::::::
REM pyinstaller
:::::::::::::::

REM Run the following line to create initial spec file
call pyinstaller EsibdExplorer.py -n "ESIBD Explorer" --noconsole --clean --icon=media/ESIBD_Explorer.ico --add-data="media;media" --add-data="plugins;plugins" --add-data="docs/_build;docs" --noconfirm --additional-hooks-dir=./pyinstaller_hooks
REM --additional-hooks-dir=./pyinstaller_hooks -> add any modules that plugins may require at run time
REM --onefile meant for release to make sure all dependencies are included in the exe but extracting everything from one exe on every start is unacceptably slow. For debugging use --onedir (default) Use this option only when you are sure that it does not limit performance or complicates debugging
REM --noconsole # console can be useful for debugging. start .exe from command window to keep errors visible after crash

REM Modify spec file if needed
REM check explicit use of paths relative to root

REM After modifying the spec file only use the following to not overwrite your changes.
REM call pyinstaller ESIBD_Explorer.spec
REM Note: I do not modify the spec file manually and use the one generated by the line above as it is.

::::::::
REM PyPI
::::::::

python -m build

REM twine upload -r testpypi dist/*

REM twine upload dist/*

::::::::::::::::
REM InstallForge
::::::::::::::::

REM Next, create setup.exe using InstallForge
REM use EsibdExplorer.ifp and adjust absolute file paths for dependencies and setup file if applicable
REM NOTE without certificate users will see "publisher unknown" message during installation. $300 per year for certificate -> only if number of clients increases
REM NOTE https://installforge.net/support1/docs/setting-up-visual-update-express/ -> for small user groups installing from downloaded exe acceptable and less error prone (e.g. if online links should change). If applicable do manual uninstall before installing from exe to get clean installation.

cmd /k REM keep batch open to see potential build errors
