# keep separate from pyproject.toml -> clear separation, easier to share
# Exclude a variety of commonly ignored directories.
exclude = [
    ".pyinstaller_hooks",  # added
    ".pyinstaller_dist",  # added
    ".pyinstaller_build",  # added
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

include = ["esibd/**/*.py", "../ESIBD_Explorer_user/plugins/**/*.py"]

# Same as Black.
line-length = 180  # increased
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[lint]
preview = true
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
# select = ["A001", "ANN204", "B905", "C403", "C408", "C419", "COM812", "COM819", "D102", "D204", "D205", "D208", "D209", "D210", "D301", "D400",
# "D401", "D404", "D417", "E4", "E7", "E9", "E117", "E202", "E203", "E225", "E226", "E228", "E231", "E251", "E252", "E261", "E262", "E265",
# "E275", "E301", "E302", "ERA001", "F", "I001", "ISC003", "PIE790", "PERF401", "PLC1901", "PLR0911", "PLR0917", "PLR2044", "PLR6104", "PLR6201", "PLW0177", "PTH201", "PTH123", "RET504",
# "RUF005", "RUF013", "RUF052", "RUF100", "SIM018", "SIM212", "SIM401", "T201", "TRY300", "UP039", "UP012", "W605"]
select = ["ALL"]  # temporary use this to explore more rules and pick which ones to keep above
ignore = [
"ANN002", "ANN003",  # args and kwargs are used just to pass anything on, no need to reproduce documentation of parent class as it should be inherited.
"CPY001", # do not use copy right notice in all files
"D100",  # usually modules will have a single class, making a module docstring redundant
"DOC201", "DOC402",  # only considers google doc strings but I use sphinx
"DTZ005", "DTZ006", # It is very unlikely that experiments will span timezones.
                    # The time in the log is usually not mission critical but the relative time in the scans which is independent of the time zone.
                    # Considering the overhead of managing both local and utc timestamps I will stick to local only until there is a use case.
"F405",  # ignoring star import warning
"FBT001", "FBT002",  # in general, avoiding booleans as positional arguments is not possible. keeping "FBT003" to make sure they are called with keywords and not positional
"N802", "N803", "N806", "N815", "N816",  # using camel case required due to PyQt
"PLR6301",  # functions that do not use self may be used as it is intuitive to use them directly on an instance. also self may be used in inherited versions
"S101",  # assertions are only used to help with static type checking
"S311",  # random numbers not used for cryptographic purposes
"UP037", # quotes needed for sphinx
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"!esibd/{config.py,const.py,core.py,plugins.py}" = ["ANN001", "D101" , "D102", "D103", "D106", "D107"]  # ignore everywhere but here -> avoids false positives if parent method has types annotated
"esibd/devices/*.py" = ["FIX002", "TD002", "TD003", "TD004"]  # No authors or issue links for TODOs. TODOs here are instructions for plugin developers.
"esibd/examples/*.py" = ["FIX002", "TD002", "TD003", "TD004"]  # No authors or issue links for TODOs. TODOs here are instructions for plugin developers.
"plugins_external/*.py" = ["FIX002", "TD002", "TD003", "TD004"]  # No authors or issue links for TODOs. TODOs here are instructions for plugin developers.

[lint.flake8-quotes]
inline-quotes = "single"

# [pydocstyle]
#     convention = "sphinx" TODO enable once available

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"