# keep separate from pyproject.toml -> clear separation, easier to share
# Exclude a variety of commonly ignored directories.
exclude = [
    ".pyinstaller_hooks",  # added
    ".pyinstaller_dist",  # added
    ".pyinstaller_build",  # added
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

include = ["esibd/**/*.py", "../ESIBD_Explorer_user/plugins/**/*.py"]

# Same as Black.
line-length = 140  # increased
indent-width = 4

# Assume Python 3.12
target-version = "py312"

[lint]
preview = true
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
#"ANN001", "ANN201", "ANN202",, "DOC201"
select = ["B905", "D102", "D205", "D208", "D209", "D400", "D401", "D404", "E4", "E7", "E9", "E117", "E202", "E203", "E225", "E226", "E231", "E251", "E252", "E261", "E262", "E275", "E301", "E302", "ERA001", "F", "D417", "PLC1901", "PTH201", "T201"]
# select = ["ALL"]  # temporary use this to explore more rules and pick which ones to keep above
# "D101", "D103" , "D102",  # does not ignore child methods and classes where the parent method has a docstring -> only enable temporarily, ignore where irrelevant
# "D417"]
ignore = ["BLE001", "CPY001", "E221", "E501", "F405", "N802", "N803", "N806", "N815", "N816", "Q000", "S603", "S607", "SLF001", "ANN001", "ANN201", "ANN202", "D102"]
# Ignore `D` rules everywhere except for the `src/` directory.

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"!esibd/{config.py,const.py,core.py,plugins.py}" = ["ANN001"]  # ignore everywhere but here -> avoids false positives if parent method has types annotated

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = true

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"